- hosts: database
  become: yes
  remote_user: admin
  roles:
    - darkwizard242.python3
    - geerlingguy.pip
    - cloudalchemy.prometheus
    - galaxyproject.postgresql
    - postgresql-ca
    - database
    - idealista.timescaledb_role
    - idealista.promscale_role
    - migrate-schema
